image: emscripten/emsdk

stages:
  - Build
  - Deploy

build:
  stage: Build
  script:
    - EMSCRIPTEN_PATH=/emsdk/upstream/emscripten make
  artifacts:
    paths:
      - final/

deploy:
  stage: Deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -r -o StrictHostKeyChecking=no final/* deploy@$LANDING_PAGE_HOST_IP:/var/page
